# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there! ğŸ‘‹ğŸ» Welcome to the DevTernShip! ğŸš€âš¡ï¸
  
  Thank you and congrats ğŸ‰ for opening your very first issue in this project. Our project aims to onboard new interns, who have applied to the companies and help them understand the process and make the transition smooth.
  Please adhere to our [Code of Conduct](https://github.com/praveenscience/Internship-LMS-FrontEnd/blob/main/Code_of_Conduct.md). ğŸ‘ğŸ»
  Please make sure not to start working on the issue, unless you get assigned to it. ğŸ˜„
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there! ğŸ‘‹ Welcome to the project! ğŸ’–
  
  Thank you and congrats ğŸ‰ for opening your first pull request. Our project aims to onboard new interns, who have applied to the companies and help them understand the process and make the transition smooth.
  Please adhere to our [Code of Conduct](https://github.com/praveenscience/Internship-LMS-FrontEnd/blob/main/Code_of_Conduct.md). ğŸ™ŒğŸ» We will get back to you as soon as we can. ğŸ˜„
   
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first Pull Request! ğŸ‰ All the best for your amazing open source journey ahead. ğŸš€âš¡ï¸
